### ISSUE TITLE
Support opening multiple repositories at once

### ISSUE THREAD

**Issue by siegenthalerroger** [gitbutlerapp/gitbutler#5825]
It would be great to be able to have multiple repositories opened in parallel (akin to the "workspaces" in vscode and intelliJ). 

For example in my case I have multiple git repositories for different parts of our as-code deployment configurations (depending on what other people require access). I regularly have changes that are similar across all repositories and create an identical structure of stacked branches in each repo (e.g. maintenance/2024-12-<environment>). It would be really cool if we could have these stacked virtual branches shown as one group despite being multiple different repos in the background.

**Comment by Byron** [comment]
Thanks a lot for sharing!

Even though I would find it unlikely that GitButler could be changed to be able to support this, an alternative to that could be the ability to recreate a certain stack, along with its patches, in another repository using a (future) CLI maybe, or by exporting a file that can be imported into other repositories with the UI even.

That way it would be possible to achieve something similar with multiple Windows open. Please do let me know if I am missing a key point which wouldn't be covered by the approach I mentioned.
Thanks again.

**Comment by Rots** [comment]
I would even appreciate if I could just open multiple independent instances (gitbutler windows) on different repositories. Currently it doesn't seem to be possible (only with the separate nightly installation, but then again limited to those two).

**Comment by Caleb-T-Owens** [comment]
@Byron wasn't part of the repo lock you added intended for supporting multiple gitbutler windows?

**Comment by Byron** [comment]
GitButler has a hidden feature that allows to have multiple Windows open, one per repository. Just `Alt + Click` them in the Project selector on the left. Would that be what you had in mind, @Rots ?

**Comment by Rots** [comment]
Yes, this is exactly what I would like! Unfortunately it doesn't seem to be currently functional. Alt+Click does indeed open a new window, but it's just white blank contents with the menu bar (which is responsive). "Reload View" doesn't seem to be doing anything. The window cannot be closed. After closing the original window, the blank window becomes unresponsive. using v0.14.4 on Windows

**Comment by Byron** [comment]
Thanks a lot for reporting, and sorry for the disappointment :/. I mostly test on MacOS and there it worked and still works.

I can also reproduce the problem on Windows.
Interestingly, a couple of menu items in the new window frame affect the Window it was spawned from.

Further, when choosing "Exit" from the menu in the child Window while looking at the logs (and there are no logs in the console), I got this:

```
2025-01-12T15:25:03.225006Z  INFO list_projects: crates\gitbutler-tauri\src\projects.rs:46: close time.busy=165µs time.idle=36.0µs
2025-01-12T15:25:04.465260Z  INFO open_project_in_window: crates\gitbutler-tauri\src\window.rs:208: creating window '1736695504465' created at 'd07c9948-daa7-4452-b125-c5529b890289/board' id=d07c9948-daa7-4452-b125-c5529b890289
[C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-runtime-wry-2.1.2\src/lib.rs:4272:46] e = WebView2Error(
    TaskCanceled,
)
[2025-01-12][15:26:10][tauri_runtime_wry][ERROR] failed to create webview: WebView2 error: TaskCanceled
2025-01-12T15:26:10.032078Z  INFO open_project_in_window: crates\gitbutler-tauri\src\projects.rs:83: close time.busy=65.6s time.idle=120µs id=d07c9948-daa7-4452-b125-c5529b890289
thread 'main' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\webview2-com-0.33.0\src\callback.rs:114:1:
send over mpsc channel: SendError { .. }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at library\core\src\panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x7ff74e6e96b6 - git_odb_object_data
   1:     0x7ff74dfb1799 - git_odb_object_data
   2:     0x7ff74e6c7f67 - git_odb_object_data
   3:     0x7ff74e6ed997 - git_odb_object_data
   4:     0x7ff74e6ee959 - git_odb_object_data
   5:     0x7ff74e6ee37f - git_odb_object_data
   6:     0x7ff74e6ee30f - git_odb_object_data
   7:     0x7ff74e6ee2f6 - git_odb_object_data
   8:     0x7ff74ea281b3 - git_midx_writer_new
   9:     0x7ff74ea28235 - git_midx_writer_new
  10:     0x7ff74ea281ef - git_midx_writer_new
  11:     0x7ff74e86d52c - git_odb_object_size
  12:     0x7ff74ea1fef0 - git_midx_writer_new
  13:     0x7ff74ea1ec18 - git_midx_writer_new
  14:     0x7ffa39f5323c - ZwWaitLowEventPair
  15:     0x7ffa39e152ec - ZwWaitLowEventPair
  16:     0x7ff74e86d4d4 - git_odb_object_size
  17:     0x7ff9dcaac7da - CreateWebViewEnvironmentWithOptionsInternal
  18:     0x7ff9dcaa7595 - CreateWebViewEnvironmentWithOptionsInternal
  19:     0x7ff9dcaac61f - CreateWebViewEnvironmentWithOptionsInternal
  20:     0x7ff9dcab55fc - CreateWebViewEnvironmentWithOptionsInternal
  21:     0x7ff9dcabb682 - CreateWebViewEnvironmentWithOptionsInternal
  22:     0x7ff9dca8eedf - CreateWebViewEnvironmentWithOptionsInternal
  23:     0x7ff9dca882cb - CreateWebViewEnvironmentWithOptionsInternal
  24:     0x7ff9dca8777c - CreateWebViewEnvironmentWithOptionsInternal
  25:     0x7ff9dcc63891 - DllCanUnloadNow
  26:     0x7ff9dcc6395b - DllCanUnloadNow
[..]
```

It looks like it hangs because the webview never finishes its creation. Probably a deadlock, with the new window failing to communicate 'something' and the parent window waiting forever to be able to conclude the window creation.

**Comment by Byron** [comment]
This now working again on MacOS at least. There seem to be issues on Windows though.

> When trying to open multiple windows with Win+project selection on Windows the new window is opened, but is just blank with only the menu bar visible.

**Comment by Byron** [comment]
This is how it currently looks like on Windows. It's unclear what's causing this, unfortunately.

![Image](https://github.com/user-attachments/assets/26254065-10b7-49fd-8ba6-fab16ed378fe)

**Comment by seanf** [comment]
Even though it works on macOS, the `Alt + Click` thing is hard to discover. Something in the Project menu would help. I would never have found it without this issue discussion.

**Comment by Byron** [comment]
This is very much intentional as the feature is known to not work properly - it can freeze the UI somehow, and it seems particularly bad on Windows.
For me it's `Cmd + Click` by the way, that might have changed over time.

**Comment by seanf** [comment]
Thanks for the reply.

> This is very much intentional as the feature is known to not work properly - it can freeze the UI somehow, and it seems particularly bad on Windows. 

How bad is it? "UI might freeze" bad, or "might corrupt my history" bad?

> For me it's `Cmd + Click` by the way, that might have changed over time.

True, I'm using a PC keyboard with a MacBook (and swapped modifier keys), so yes, I should have said `Cmd + Click`.


There must be some safe way of supporting multiple repositories, even if it requires multiple independent instances running. Is that possible?

**Comment by Byron** [comment]
> How bad is it? "UI might freeze" bad, or "might corrupt my history" bad?

The UI is known to freeze up, nothing else.

> There must be some safe way of supporting multiple repositories, even if it requires multiple independent instances running. Is that possible?

You can use the Stable and Nightly release side-by-side as these are different apps technically.
And I also recommend trying the multi-window feature to see how it goes. It was working at some point, but something changed which made it freeze last time I tried.
There is no real reason this wouldn't work, it just hasn't been a priority to make it an officially supported feature.

**Comment by ringods** [comment]
`Cmd-click` seems to work fine. One small UX request though: if multiple windows are open, can these be listed in the `Window` menu item on macOS? A lot of macOS apps do this, and I became quite used to it.

**Comment by Byron** [comment]
That's great to hear!

And getting them listed there would definitely be on the list for when multi-window is officially supported.

**Comment by krlvi** [comment]
Thanks for all the discussion here. The original request—showing stacks from several repositories together in one workspace—isn't something we're planning to build.

For working across repositories in parallel, GitButler now supports opening a project in a separate window with `but gui -n <path>`. That shipped via https://github.com/gitbutlerapp/gitbutler/pull/14033 in [release 0.20.0](https://github.com/gitbutlerapp/gitbutler/releases/tag/release/0.20.0). The modifier-click shortcut in the project selector is still available too.

I'm going to close this as not planned. The remaining multi-window problems are better tracked as focused bugs or UX requests so we can act on them separately. Let me know if I missed an important use case.
